const express = require("express");
const router = express.Router();
const db = require("../config/db");
const { verifyToken, verifyAdmin } = require("../middleware/authMiddleware");
<<<<<<< HEAD
=======
const upload = require('../middleware/upload'); // Handles image uploads
>>>>>>> 2a1e0654be6f4795994a174fbf3eee304dc2bdc6

// Helper function to safely wrap error messages
const handleSqlError = (res, err) => {
    return res.status(500).json({ error: err.message || "Database operation failed" });
};

// ==========================================
// PRODUCTS ENDPOINTS
// ==========================================

// Add Product - ADMIN ONLY
<<<<<<< HEAD
router.post("/add", verifyAdmin, (req, res) => {
    const { name, description, price, stock, image } = req.body;

    // Image is now a plain URL string provided by the admin (e.g. Unsplash, Imgur, Cloudinary link)
    const imagePath = image && image.trim() !== "" ? image.trim() : null;

=======
router.post("/add", verifyAdmin, upload.single('image'), (req, res) => {
    const { name, description, price, stock } = req.body;
    
    // 1. Capture the file path generated by Multer (use fallback if no image uploaded)
    const imagePath = req.file ? `/uploads/${req.file.filename}` : null;

    // 2. Execute SQL query with imagePath mapped to your 'image' column
>>>>>>> 2a1e0654be6f4795994a174fbf3eee304dc2bdc6
    const sql = `INSERT INTO products (name, description, price, image, stock) VALUES (?, ?, ?, ?, ?)`;
    
    db.query(sql, [name, description, price, imagePath, stock], (err, result) => {
        if (err) return handleSqlError(res, err);
        res.json({ message: "Product Added Successfully", imagePath });
    });
});

// View All Products - PUBLIC
router.get("/", (req, res) => {
    const sql = "SELECT * FROM products";
    db.query(sql, (err, result) => {
        if (err) return handleSqlError(res, err);
        res.json(result);
    });
});

// Get Single Product by ID - PUBLIC
router.get("/:id", (req, res) => {
    const { id } = req.params;
    const sql = "SELECT * FROM products WHERE id=?";
    db.query(sql, [id], (err, result) => {
        if (err) return handleSqlError(res, err);
        if (result.length === 0) return res.status(404).json({ message: "Product not found" });
        res.json(result[0]);
    });
});

// Update Product - ADMIN ONLY
<<<<<<< HEAD
router.put("/update/:id", verifyAdmin, (req, res) => {
    const { id } = req.params;
    const { name, description, price, stock, image } = req.body;

    // Image is now always a plain URL string typed/pasted by the admin
    const imagePath = image && image.trim() !== "" ? image.trim() : null;

=======
router.put("/update/:id", verifyAdmin, upload.single('image'), (req, res) => {
    const { id } = req.params;
    const { name, description, price, stock, existingImage } = req.body; 
    
    // 1. If a new file binary is sent, use it. Otherwise, look for the text fallback variable.
    let imagePath = req.file ? `/uploads/${req.file.filename}` : existingImage;

    // 2. Execute SQL query cleanly
>>>>>>> 2a1e0654be6f4795994a174fbf3eee304dc2bdc6
    const sql = `UPDATE products SET name=?, description=?, price=?, image=?, stock=? WHERE id=?`;
    
    db.query(sql, [name, description, price, imagePath, stock, id], (err, result) => {
        if (err) {
            console.error("SQL Error during update:", err);
            return handleSqlError(res, err);
        }
        
        if (result.affectedRows === 0) {
            return res.status(404).json({ message: "Product not found or no updates made." });
        }
        
        res.json({ message: "Product Updated Successfully" });
    });
});



// Delete Product - ADMIN ONLY
router.delete("/delete/:id", verifyAdmin, (req, res) => {
    const { id } = req.params;
    const sql = "DELETE FROM products WHERE id=?";
    db.query(sql, [id], (err, result) => {
        if (err) return handleSqlError(res, err);
        res.json({ message: "Product Deleted Successfully" });
    });
});

// Stock Management - SECURE USER / CHECKOUT
router.put("/stock", verifyToken, (req, res) => {
    const items = req.body;
    
    if (!Array.isArray(items) || items.length === 0) {
        return res.status(400).json({ message: "Invalid items structure supplied." });
    }

    const sql = "UPDATE products SET stock = stock - ? WHERE id = ?";
    let completed = 0;
    let hasErrorOccurred = false;

    items.forEach(item => {
        db.query(sql, [item.quantity, item.product_id], (err) => {
            if (hasErrorOccurred) return; 

            if (err) {
                hasErrorOccurred = true;
                return handleSqlError(res, err);
            }

            completed++;
            if (completed === items.length) {
                res.json({ message: "Stock Updated" });
            }
        });
    });
});

// ==========================================
// REVIEWS ENDPOINTS
// ==========================================

// Get reviews for a specific item
router.get("/:id/reviews", (req, res) => {
    const { id } = req.params;
    const sql = `SELECT reviews.*, users.name FROM reviews JOIN users ON reviews.user_id = users.id WHERE product_id = ? ORDER BY reviews.created_at DESC`;
    db.query(sql, [id], (err, result) => {
        if (err) return handleSqlError(res, err);
        res.json(result);
    });
});

// Add Review - LOGGED IN USERS ONLY
router.post("/:id/reviews", verifyToken, (req, res) => {
    const { id } = req.params;
    const { rating, comment } = req.body; 
    const user_id = req.user.id; 

    const checkSql = `SELECT * FROM reviews WHERE user_id = ? AND product_id = ?`;
    db.query(checkSql, [user_id, id], (err, result) => {
        if (err) return handleSqlError(res, err);
        if (result.length > 0) return res.status(400).json({ message: "You have already reviewed this product." });

        const insertSql = `INSERT INTO reviews (user_id, product_id, rating, comment) VALUES (?, ?, ?, ?)`;
        db.query(insertSql, [user_id, id, rating, comment], (err) => {
            if (err) return handleSqlError(res, err);
            res.json({ message: "Review Added Successfully" });
        });
    });
});

// Update a Review
router.put("/:id/reviews", verifyToken, (req, res) => {
    const { id } = req.params;
    const { rating, comment } = req.body;
    const user_id = req.user.id;
    const sql = `UPDATE reviews SET rating = ?, comment = ? WHERE user_id = ? AND product_id = ?`;
    db.query(sql, [rating, comment, user_id, id], (err) => {
        if (err) return handleSqlError(res, err);
        res.json({ message: "Review Updated" });
    });
});

// Delete a Review
router.delete("/reviews/:reviewId", verifyToken, (req, res) => {
    const { reviewId } = req.params;
    const sql = "DELETE FROM reviews WHERE id = ?";
    db.query(sql, [reviewId], (err) => {
        if (err) return handleSqlError(res, err);
        res.json({ message: "Review Deleted Successfully" });
    });
});

module.exports = router;